server:
  port: 20001
  # 在返回给页面的结果里，把错误信息添加到 message 里
  error:
    include-message: always

spring:
  application:
    name: coupon-customer-serv
  datasource:
    # mysql 数据源
    username: root
    password: oQ2a9sCR
    url: jdbc:mysql://127.0.0.1:3306/coupon_center_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      pool-name: CouponCenterHikari
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 60000
      auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      # 在生产环境全部为 none，防止 ddl 结构被自动执行
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  cloud:
    nacos:
      discovery:
        # nacos 的服务注册地址，可以配置多个 , 逗号分隔
        server-addr: localhost:8848
        # 服务注册到 nacos 上的名称，一般不用配置
        service: coupon-customer-serv
        # nacos 客户端向服务端发送心跳的时间间隔，时间单位其实是 ms
        heart-beat-interval: 5000
        # 服务端没有接受到客户端心跳请求就将其设为不健康的时间间隔，默认为 15s
        # 注：推荐值该值为 15s 即可，如果有的业务线希望服务下线或者出故障时希望尽快被发现，可以适当减少该值
        heart-beat-timeout: 20000
        # 元数据部分 - 可以自己随便定制
        metadata:
          mydata: abc
        # 客户端在启动时是否读取本地配置项（一个文件）来获取服务列表
        # 注：推荐该值为 false，若改成 true。
        # 则客户端会在本地的一个文件中保存服务信息，当下次宕机启动时，会优先读取本地的配置对外提供服务
        naming-load-cache-at-start: false
        # 命名空间 ID，nacos 通过不同的命名空间来区分不同的环境，进行数据隔离
        namespace: dev
        # 创建不同的集群
        cluster-name: Cluster-A
        # 【注意】两个服务如果存在上下游调用关系，必须配置相同的 group 才能发起访问
        group: myGroup
        # 向注册中心注册服务，默认为 true
        # 如果只消费服务，不作为服务提供方，倒是可以设置成 false，减少开销
        register-enabled: true

logging:
  level:
    com.broadview.coupon: debug